branches:
  only:
    - master
language: go
sudo: false
go:
- 1.5
- tip
cache:
  directories:
  - $HOME/local
before_install:
- ./.travis.build-protoc.sh 3.0.0-beta-1
- go get github.com/golang/lint/golint
install:
- go get github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
script:
- make examples
- test -z "$(git -C $GOPATH/src/github.com/gengo/grpc-gateway status --porcelain)"
- go test -v github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/... --logtostderr
- golint github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/...
- golint github.com/gengo/grpc-gateway/runtime/...
- golint github.com/gengo/grpc-gateway/utilities/...
- go vet github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/...
- go vet github.com/gengo/grpc-gateway/runtime/...
- go vet github.com/gengo/grpc-gateway/utilities/...
env:
  global:
  - "PATH=$PATH:$HOME/local/bin"
