language: go

go:
- 1.3
- tip
before_install:
- cd /tmp
- wget https://github.com/google/protobuf/archive/v3.0.0-alpha-2.tar.gz
- tar xvzf v3.0.0-alpha-2.tar.gz
- cd protobuf-3.0.0-alpha-2
- ./autogen.sh
- ./configure
- make
- sudo make install
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/vet
install:
- go get github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
script:
- make examples
- test -z "$(git -C $GOPATH/src/github.com/gengo/grpc-gateway status --porcelain)"
- go test -v github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/... --logtostderr
- golint github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
- golint github.com/gengo/grpc-gateway/runtime
- go tool vet $GOPATH/src/github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
- go tool vet $GOPATH/src/github.com/gengo/grpc-gateway/runtime
